

<div class="row">
	<div class="col-md-12"> 
		<div class="tab-content">
            <!----TABLE LISTING STARTS-->
            <div class="tab-pane box active" id="list" style="width:100%;">
            
          
                <table class="table datatable table" border="0" cellpadding="0" cellspacing="0" style="width:100%; font-family:Arial, Helvetica, sans-serif; font-size:14px; letter-spacing:0.5;" id="table_export">
                	<thead>
                    <tr>
                            <td colspan="3">
                                <table width="100%">
                                    <tr>
                                        <td width="33.33%"  valign="middle" align="left";><div><?php  $image = base_url().'/uploads/system_image/1.jpg'; ?>
                                        <img src="<?php echo $image; ?>" width="80" height="70" /></div></td>
                                        <td width="33.33%" valign="middle" align="center"><div style="font-size:1.8em; text-align:center; font-weight:600; color:#000;">Page Inc School</div></td>
                                        <td width="33.33%" valign="bottom" align="right" style="font-size:12px;"><div>Date : <?php echo date('jS M Y'); ?> </div></td>     
                                    </tr>
                                </table>
                            </td>
                    </tr>
                        
                        <tr bgcolor="#000000"><td colspan="3" style="font-size:1.3em; text-align:center; font-weight:600; padding:6px 0px; color:#FFF;">Group Listing</td></tr>
                        <tr bgcolor="#000000">
                            <td colspan="3" style="font-size:1.2em; text-align:center; font-weight:600; padding:6px 0px; color:#FFF;"></td>
                        </tr>                         
                		
                        <tr bgcolor="#2092D0">
                    		<th style="color:#FFF; border-right:1px solid #EEE;  text-align:center; padding:6px 0px;  border-top:1px solid #eee; line-height:20px; width:5%; ">No</th>
                    		<th style="color:#FFF; border-right:1px solid #EEE;  text-align:center; padding:6px 0px;  border-top:1px solid #eee;  line-height:20px; width:15%;">Group name</th>
                    		<th style="color:#FFF; border-right:1px solid #EEE;  text-align:center; padding:6px 0px;  border-top:1px solid #eee;  line-height:20px; width:80%; ">Assigned Modules</th>  
						</tr>

					</thead>
                    <tbody>
                    	<?php 
							$group = $this->db->get('group')->result_array();
						$count = 1;
						
						foreach($group as $row):	
						
							if($row['user_type'] == 1){								
						
								$u_type  = 'Teacher';
								
								
							}elseif($row['user_type'] == 2){
								$u_type  = 'Student';
							}elseif($row['user_type'] == 3){
								$u_type  = 'Non-Teaching';
							}elseif($row['user_type'] == 4){
								$u_type  = 'Parent';
							}
							$modules = $this->db->get_where("assign_module",array("group_id"=>$row['user_type']))->result_array();
						
							$module_id = $modules[0]['module_id'];
							$mod = explode(",",$module_id);
							foreach($mod as $modu):
							
							$getmod = $this->db->get_where("modules",array("module_id"=>$modu))->result_array();
							
							$get[]  = $getmod[0]['module_name'];
							
							endforeach;
							$all_modules = implode(",",$get);
						
					
							
							
							if($row['group_id']!='1' && $row['group_id']!='2')
							{
						?>
                        <tr>
                            <td align="center" style="font-size:11px; padding:6px 2px; border-bottom:1px solid #EEE; border-left:1px solid #EEE; border-right:1px solid #EEE; width:5%; "><?php echo $count++;?></td>
							<td align="center" style="font-size:12px; padding:6px 2px; border-bottom:1px solid #EEE; border-left:0px solid #EEE; border-right:0px solid #EEE; width:15%; "><?php echo $row['group_name'];?></td>
							<td align="center" style="font-size:12px; padding:6px 2px; border-bottom:1px solid #EEE; border-left:0px solid #EEE; border-right:0px solid #EEE; width:80%; "><?php echo $all_modules;?></td>
                        </tr>
                        <?php 
						}
							$get = '';
							$all_modules = '';						
						endforeach; 
						
						?>
                    </tbody>
                    
                     <tr>
                        <td valign="middle" align="right" colspan="3" style="padding:12px 0px; border-top:2px solid #2092D0; font-size:10px;"><span style="color:#2092D0;">Generated By : </span> <?php echo $this->session->userdata('name');?> </td>
                        </tr>
                    	
                </table>
                
			</div>
            <!----TABLE LISTING ENDS--->
		</div>
	</div>
</div>



