

<div class="row">
	<div class="col-md-12"> 
		<div class="tab-content">
            <!----TABLE LISTING STARTS-->
            <div class="tab-pane box active" id="list" style="width:100%;">
            
          
                 <table class="table datatable table" border="0" cellpadding="0" cellspacing="0" style="width:100%; font-family:Arial, Helvetica, sans-serif; font-size:14px; letter-spacing:0.5;" id="table_export">
                	<thead>
                        <tr>
                            <td colspan="3">
                                <table width="100%">
                                    <tr>
                                        <td width="33.33%"  valign="middle" align="left";><div><?php  $image = base_url().'/uploads/system_image/1.jpg'; ?>
                                        <img src="<?php echo $image; ?>" width="80" height="70" /></div></td>
                                        <td width="33.33%" valign="middle" align="center"><div style="font-size:1.8em; text-align:center; font-weight:600; color:#000;">Page Inc School</div></td>
                                        <td width="33.33%" valign="bottom" align="right" style="font-size:12px;"><div>Date : <?php echo date('jS M Y'); ?> </div></td>     
                                    </tr>
                                </table>
                            </td>
                        </tr>
                    
                        <tr><td colspan="3" style="height:15px;"></td></tr>
                        <tr bgcolor="#000000"><td colspan="3" style="font-size:1.2em; text-align:center; font-weight:600; padding:6px 0px; color:#FFF;">Notification Listing</td></tr>
                		
                        <tr bgcolor="#2092D0">
                    		<th style="color:#FFF; padding:6px 6px;border-top:1px solid #eee;" width="5%">No</th>
                    		<th style="color:#FFF; padding:6px 6px;border-top:1px solid #eee;" width="25%">Notification Name</th>
                    		<th style="color:#FFF; padding:6px 6px;border-top:1px solid #eee;" width="70%">Notice</th>  
						</tr>
					</thead>
                    <tbody>
                    	<?php 
						$noticeboard = $this->db->get('noticeboard')->result_array();
						$count = 1;
						if(count($noticeboard) > 0){
						foreach($noticeboard as $row):?>
                        <tr>
                            <td valign="middle" align="center"  style="font-size:13px; padding:6px 6px; border-bottom:1px solid #EEE; border-left:1px solid #EEE; border-right:1px solid #EEE;" width="5%"><?php echo $count++;?></td>							
							<td valign="middle" align="center" style="font-size:13px; padding:6px 6px; border-bottom:1px solid #EEE; border-left:0px solid #EEE; border-right:0px solid #EEE;" width="25%"><?php echo $row['notice_name'];?></td>
							<td valign="middle" align="left" style="font-size:13px; line-height:18px; padding:6px 6px; border-bottom:1px solid #EEE; border-left:1px solid #EEE; border-right:1px solid #EEE;" width="70%"><?php echo $row['notice'];?></td>							
                        </tr>
                        <?php endforeach;
						}
						else
						{
						?>	
						<tr><td align="left" style="font-size:13px; line-height:18px;" colspan="3">*No record found..</td></tr>
						<?php 
						}
						?>
                    </tbody>
					<tr>
                        <td valign="middle" align="right" colspan="3" style=" padding:12px 0px; border-top:2px solid #2092D0; font-size:10px; text-align:right; "><span style="color:#2092D0;">Generated By : </span> <?php echo $this->session->userdata('name');?> </td>
                        </tr>
                </table>
                
			</div>
            <!----TABLE LISTING ENDS--->
		</div>
	</div>
</div>



