<div class="row">
	<div class="col-md-12"> 
		<div class="tab-content">
            <!----TABLE LISTING STARTS-->
            <div class="tab-pane box active" id="list" style="width:100%;">
                <table class="table datatable table" border="0" cellpadding="0" cellspacing="0" style="width:100%; font-family:Arial, Helvetica, sans-serif; font-size:14px; letter-spacing:0.5;" id="table_export">
                	<thead>
                    <tr>
                            <td colspan="5">
                                <table width="100%">
                                    <tr>
                                        <td width="33.33%"  valign="middle" align="left";><div><?php  $image = base_url().'/uploads/system_image/1.jpg'; ?>
                                        <img src="<?php echo $image; ?>" width="80" height="70" /></div></td>
                                        <td width="33.33%" valign="middle" align="center"><div style="font-size:1.8em; text-align:center; font-weight:600; color:#000;">Page Inc School</div></td>
                                        <td width="33.33%" valign="bottom" align="right" style="font-size:12px;"><div>Date : <?php echo date('jS M Y'); ?> </div></td>     
                                    </tr>
                                </table>
                            </td>
                    </tr>                   
                        <tr><td colspan="5" style="height:15px;"></td></tr>
                       <tr bgcolor="#000000"><td colspan="5" style="font-size:1.2em; text-align:center; font-weight:600; padding:6px 0px; color:#FFF;">Subject Wise Toppers </td></tr>
                       <tr bgcolor="#000000" colspan="5">
                		   <td colspan="5" style="font-size:1.0em; text-align:center; font-weight:600; padding:6px 0px; color:#FFF;">
                            <?php 							
				echo ucwords("Standard : <span style='text-align:right;color:#2092D0;font-size:1.2em;font-weight:600;'>".$standard."</span>"); ?>
                            </td>
                        </tr>   
                		
                        <tr bgcolor="#2092D0">
                    		<th style="color:#FFF; padding:6px 0px;" width="20%">Subject Name</th>
                            <th style="color:#FFF; padding:6px 0px;" width="20%">Student Name</th>
                                                        <th style="color:#FFF; padding:6px 0px;" width="20%">Class Name</th>
                    		<th style="color:#FFF; padding:6px 0px;" width="20%">Marks</th>
                    		<th style="color:#FFF; padding:6px 0px;" width="20%">Out of Marks</th>
                     	</tr>
					</thead>
                    <tbody>
                    	<?php 
					
					$mark = $this->db->query("SELECT DISTINCT(s1.student_id), s1.subject_id, s2.mks, s1.student_name, e.out_of_marks, s1.class_id FROM mark s1, ( SELECT s.subject_id, MAX( s.mark_obtained ) AS mks,s.subject_name FROM mark s GROUP BY s.subject_id )s2 left join exam e ON e.subject_id = s2.subject_name WHERE s1.subject_id = s2.subject_id AND s1.mark_obtained = s2.mks AND s1.class_id =".intval($standard)." ORDER BY s1.subject_id ASC")->result_array();
					
						foreach($mark as $row_mark):	?>
                        <tr>
                            <td align="center" style="font-size:11px; padding:6px 0px; border-bottom:1px solid #EEE; border-left:1px solid #EEE; border-right:1px solid #EEE;" width="10%"><?php echo  $row_mark['subject_id'];?></td>
                             <td align="center" style="font-size:11px; padding:6px 0px; border-bottom:1px solid #EEE; border-left:1px solid #EEE; border-right:1px solid #EEE;" width="10%"><?php echo  $row_mark['student_name'];?></td>
                                 <td align="center" style="font-size:11px; padding:6px 0px; border-bottom:1px solid #EEE; border-left:1px solid #EEE; border-right:1px solid #EEE;" width="10%"><?php echo  $row_mark['class_id'];?></td>
							<td align="center" style="font-size:11px; padding:6px 0px; border-bottom:1px solid #EEE; border-left:0px solid #EEE; border-right:0px solid #EEE;" width="25%" ><?php echo $row_mark['mks'];?></td>
							<td align="center" style="font-size:11px; padding:6px 0px; border-bottom:1px solid #EEE; border-left:0px solid #EEE; border-right:0px solid #EEE;" width="25%"><?php echo  $row_mark['out_of_marks'];?></td>
                        </tr>
                        <?php endforeach; ?>
                    </tbody>
                    
                     <tr>
                        <td valign="middle" align="right" colspan="5" style="padding:12px 0px; border-top:2px solid #2092D0; font-size:10px;"><span style="color:#2092D0;">Generated By : </span> <?php echo $this->session->userdata('name');?> </td>
                        </tr>
                    	
                </table>
                
			</div>
            <!----TABLE LISTING ENDS--->
		</div>
	</div>
</div>



