<div class="row">
	<div class="col-md-12"> 
		<div class="tab-content">
            <!----TABLE LISTING STARTS-->
            <div class="tab-pane box active" id="list" style="width:100%;">
                <table class="table datatable table" border="0" cellpadding="0" cellspacing="0" style="width:100%; font-family:Arial, Helvetica, sans-serif; font-size:14px; letter-spacing:0.5;" id="table_export">
                	<thead>
                   <tr>
                            <td colspan="4">
                                <table width="100%">
                                    <tr>
                                        <td width="33.33%"  valign="middle" align="left";><div><?php  $image = base_url().'/uploads/system_image/1.jpg'; ?>
                                        <img src="<?php echo $image; ?>" width="80" height="70" /></div></td>
                                        <td width="33.33%" valign="middle" align="center"><div style="font-size:1.8em; text-align:center; font-weight:600; color:#000;">Page Inc School</div></td>
                                        <td width="33.33%" valign="bottom" align="right" style="font-size:12px;"><div>Date : <?php echo date('jS M Y'); ?> </div></td>     
                                    </tr>
                                </table>
                            </td>
                    </tr>  
                        <tr><td colspan="4" style="height:15px;"></td></tr>
                         <tr bgcolor="#000000"><td colspan="4" style="font-size:1.2em; text-align:center; font-weight:600;  color:#FFF;">Class Wise Teacher Listing</td></tr>
                          <tr bgcolor="#000000"><td colspan="4" style="font-size:1.0em; border-top:1px solid #FFF; text-align:center; font-weight:600;  color:#FFF;  padding:6px 0px;"> <?php echo ucwords('Class Name : <span style="text-align:right;color:#2092D0;font-size:1.0em;font-weight:600;">'.$class_id.'</span>'); ?></td></tr>
                		
                         <tr bgcolor="#2092D0">
                        <th style="color:#FFF; border-right:1px solid #EEE; border-left:1px solid #EEE; padding:6px 2px; font-size:13px; text-align:center;">Full Name</th>	
                       <th style="color:#FFF; border-right:1px solid #EEE;padding:6px 2px;  font-size:13px; text-align:center;">Designation</th>  	
                       <th style="color:#FFF; border-right:1px solid #EEE;padding:6px 2px;  font-size:13px; text-align:center;">Phone</th> 
                       <th style="color:#FFF; border-right:1px solid #EEE; padding:6px 2px;  font-size:13px; text-align:center;">Email</th> 
                    		
						</tr>
                       
					</thead>
                    <tbody>
                    	<?php 
						
						//$this->db->()
						
						$this->db->select('teacher_class_association.class_id as sclass_id,teacher.name as teacher_name,teacher.email,teacher.phone,teacher.designation');
						$this->db->join('teacher', 'teacher_class_association.teacher_id = teacher.teacher_id');
				
						$non_tech = $this->db->get_where('teacher_class_association', array('teacher_class_association.class_id' => $class_id))->result_array();
						
						$count = 1;
						
					
						foreach($non_tech as $rowtech):	
					
						?>
                        <tr>
                          
							<td align="center" style="font-size:13px; padding:6px 2px; border-bottom:1px solid #EEE; border-left:1px solid #EEE; border-right:0px solid #EEE;"><?php echo $rowtech['teacher_name'];?></td>
							<td align="center" style="font-size:13px; padding:6px 2px; border-bottom:1px solid #EEE; border-left:1px solid #EEE; border-right:0px solid #EEE;"><?php echo $rowtech['designation'];?></td>
							<td align="center" style="font-size:13px; padding:6px 2px; border-bottom:1px solid #EEE; border-left:1px solid #EEE; border-right:0px solid #EEE;"><?php echo $rowtech['phone'];?></td>
                            <td align="center" style="font-size:13px; padding:6px 2px; border-bottom:1px solid #EEE; border-left:1px solid #EEE; border-right:1px solid #EEE;"><?php echo $rowtech['email'];?></td>
                            
                        </tr>
                        
                         <?php endforeach;?>
                      
						
                    </tbody>
                    
                     <tr>
                        <td valign="middle" align="right" colspan="4" style="padding:12px 0px; border-top:2px solid #2092D0; font-size:10px;"><span style="color:#2092D0;">Generated By : </span> <?php echo $this->session->userdata('name');?> </td>
                        </tr>
                    	
                </table>
                
			</div>
            <!----TABLE LISTING ENDS--->
		</div>
	</div>
</div>



