<div class="row">
	<div class="col-md-12"> 
		<div class="tab-content">
            <!--TABLE LISTING STARTS-->
            <div class="tab-pane box active" id="list" style="width:100%;">
                <table class="table datatable table" border="0" cellpadding="0" cellspacing="0" style="width:100%; font-family:Arial, Helvetica, sans-serif; font-size:14px; letter-spacing:0.5;" id="table_export">
                	<thead>
                   <tr>
                            <td colspan="2">
                                <table width="100%">
                                    <tr>
                                        <td width="33.33%"  valign="middle" align="left";><div><?php  $image = base_url().'/uploads/system_image/1.jpg'; ?>
                                        <img src="<?php echo $image; ?>" width="80" height="70" /></div></td>
                                        <td width="33.33%" valign="middle" align="center"><div style="font-size:1.8em; text-align:center; font-weight:600; color:#000;">Page Inc School</div></td>
                                        <td width="33.33%" valign="bottom" align="right" style="font-size:12px;"><div>Date : <?php echo date('jS M Y'); ?> </div></td>     
                                    </tr>
                                </table>
                            </td>
                    </tr> 
                        <tr><td colspan="2" style="height:15px;"></td></tr>
                        <tr bgcolor="#000000"><td colspan="2" style="font-size:1.2em; text-align:center; font-weight:600; padding:6px 0px; color:#FFF;">Top Three student of class <?php echo $class_id; ?></td></tr>                		
                        <tr bgcolor="#2092D0">
                    		<th style="color:#FFF; padding:6px 3px; text-align:center;">Student Name</th>
                    		<th style="color:#FFF; padding:6px 3px;text-align:center;">Total Percentage</th>                    	
                     	</tr>
					</thead>
                    <tbody>
                    	<?php 
						
				$mark = $this->db->query("SELECT SUM(mark.mark_obtained) as total,SUM(exam.out_of_marks) as outmark,mark.student_id FROM mark JOIN exam ON exam.subject_id=mark.subject_name WHERE mark.class_id='".$class_id."' AND mark.exam_id='".$exam_id."' GROUP BY mark.student_id ORDER BY mark.mark_obtained DESC LIMIT 0,3")->result_array();
					
				
						foreach($mark as $row_mark):
						
					$total = ($row_mark['total']*100/$row_mark['outmark']);
						$total = number_format($total, 2, '.', ',');
						
						$student = $this->db->get_where("student",array('student_id'=>$row_mark['student_id']))->result_array();
						?>
                        <tr>
                            <td align="center" style="font-size:11px; padding:6px 3px; border-bottom:1px solid #EEE; border-left:1px solid #EEE; border-right:1px solid #EEE;" ><?php echo  $student[0]['name'];?></td>
							<td align="center" style="font-size:11px; padding:6px 3px; border-bottom:1px solid #EEE; border-left:0px solid #EEE; border-right:1px solid #EEE;"  ><?php echo $total.'%'; //$row_mark['total'];?></td>							
                        </tr>
                        <?php endforeach; ?>
                    </tbody>
                    
                     <tr>
                        <td valign="middle" align="right" cospan="2" style="padding:12px 0px; border-top:2px solid #2092D0; font-size:10px;"><span style="color:#2092D0;">Generated By : </span> <?php echo $this->session->userdata('name');?> </td>
                    </tr>
                    	
                </table>
                
			</div>
            <!--TABLE LISTING ENDS-->
		</div>
	</div>
</div>



