<div class="row">
	<div class="col-md-12"> 
		<div class="tab-content">
            <!----TABLE LISTING STARTS-->
            <?php 
            $res = $this->db->get_where("student",array("student_id"=>$student_id))->result_array();

		  			if(!empty($res))
					{
						$student_name = $res[0]['name'];
						}
						else{
							$student_name = '';
							}
							?>
            <div class="tab-pane box active" id="list" style="width:100%;">
                <table class="table datatable table" border="0" cellpadding="0" cellspacing="0" style="width:100%; font-family:Arial, Helvetica, sans-serif; font-size:14px; letter-spacing:0.5;" id="table_export">
                	<thead>
                   <tr>
                            <td colspan="3">
                                <table width="100%">
                                    <tr>
                                        <td width="33.33%"  valign="middle" align="left";><div><?php  $image = base_url().'/uploads/system_image/1.jpg'; ?>
                                        <img src="<?php echo $image; ?>" width="80" height="70" /></div></td>
                                        <td width="33.33%" valign="middle" align="center"><div style="font-size:1.8em; text-align:center; font-weight:600; color:#000;">Page Inc School</div></td>
                                        <td width="33.33%" valign="bottom" align="right" style="font-size:12px;"><div>Date : <?php echo date('jS M Y'); ?> </div></td>     
                                    </tr>
                                </table>
                            </td>
                    </tr>
                        <tr><td colspan="3" style="height:15px;"></td></tr>
                        <tr bgcolor="#000000"><td colspan="3" style="font-size:1.2em; text-align:center; font-weight:600; padding:6px 0px; color:#FFF;">Student Mark Sheet </td></tr>
                           <tr bgcolor="#000000"><td colspan="3" style="font-size:1.0em; text-align:center; font-weight:600;  color:#FFF;  padding:6px 0px;"> <?php echo ucwords('Student Name : <span style="text-align:right;color:#2092D0;font-size:1.0em;font-weight:600;">'.$student_name.'</span>'); ?></td></tr>                       
                		
                        <tr bgcolor="#2092D0">
                    		<th style="color:#FFF; padding:6px 3px;" width="20%">Subject</th>
                    		<th style="color:#FFF; padding:6px 3px;" width="40%">Mark</th>
                    		<th style="color:#FFF; padding:6px 3px;" width="40%">Out of Marks</th>
                    	</tr>
					</thead>
                    <tbody>
                    	<?php 
						//$this->db->select('subject.name as subject_name,exam.name as exam_name,exam.class_id,exam.subject_id,exam.date,exam.time_start,exam.time_end');
						$mark = $this->db->query("SELECT mark.subject_name,mark.mark_obtained,exam.out_of_marks FROM mark JOIN exam ON mark.subject_name=exam.subject_id WHERE mark.class_id='".$class_id."' AND mark.exam_id='".$exam_id."' AND student_id='".$student_id."'")->result_array();
						
							foreach($mark as $row_mark):	
							$subject = $this->db->get_where("subject",array("subject_id"=>$row_mark['subject_name']))->row();
						?>
                        <tr>
                            <td align="center" style="font-size:11px; padding:6px 3px; border-bottom:1px solid #EEE; border-left:1px solid #EEE; border-right:1px solid #EEE;" width="20%"><?php echo $subject->name;?></td>
							<td align="center" style="font-size:11px; padding:6px 3px; border-bottom:1px solid #EEE; border-left:0px solid #EEE; border-right:0px solid #EEE;" width="40%" ><?php echo $row_mark['mark_obtained'];?></td>
							<td align="center" style="font-size:11px;padding:6px 3px; border-bottom:1px solid #EEE; border-left:0px solid #EEE; border-right:0px solid #EEE;" width="40%"><?php echo $row_mark['out_of_marks'];?></td>
                        </tr>
                        <?php endforeach; ?>
                    </tbody>
                    
                     <tr>
                        <td valign="middle" align="right" colspan="3" style="padding:12px 2px; border-top:2px solid #2092D0; font-size:10px;"><span style="color:#2092D0;">Generated By : </span> <?php echo $this->session->userdata('name');?> </td>
                        </tr>
                    	
                </table>
                
			</div>
            <!----TABLE LISTING ENDS--->
		</div>
	</div>
</div>



