<div class="row">
	<div class="col-md-12"> 
		<div class="tab-content">
            <!----TABLE LISTING STARTS-->
            <div class="tab-pane box active" id="list" style="width:100%;">
                <table class="table datatable table" border="0" cellpadding="0" cellspacing="0" style="width:100%; font-family:Arial, Helvetica, sans-serif; font-size:14px; letter-spacing:0.5;" id="table_export">
                	<thead>
                   <tr>
                            <td colspan="4">
                                <table width="100%">
                                    <tr>
                                        <td width="33.33%"  valign="middle" align="left";><div><?php  $image = base_url().'/uploads/system_image/1.jpg'; ?>
                                        <img src="<?php echo $image; ?>" width="80" height="70" /></div></td>
                                        <td width="33.33%" valign="middle" align="center"><div style="font-size:1.8em; text-align:center; font-weight:600; color:#000;">Page Inc School</div></td>
                                        <td width="33.33%" valign="bottom" align="right" style="font-size:12px;"><div>Date : <?php echo date('jS M Y'); ?> </div></td>     
                                    </tr>
                                </table>
                            </td>
                    </tr>
                        <tr><td colspan="4" style="height:15px;"></td></tr>
                        <?php $exam_title = $this->db->get_where('exam',array('exam.class_id'=>$class_id,'exam.exam_id'=>$exam_id))->row();?>
                        <tr bgcolor="#000000"><td colspan="4" style="font-size:1.2em; text-align:center; font-weight:600; padding:6px 0px; color:#FFF;">Exam Time Table</td></tr>
                        <tr bgcolor="#000000"><td colspan="4" style="font-size:1.0em; border-top:1px solid #EEE; text-align:center; font-weight:600;  color:#FFF;  padding:6px 0px;"> <?php  echo ucwords('Exam : <span style="text-align:right;color:#2092D0;font-size:1.0em;font-weight:600;">'.$exam_title->name.'</span>'); ?></td></tr>
                		
                        <tr bgcolor="#2092D0">
                    		<th style="color:#FFF; padding:6px 0px;" width="20%">Subject</th>
                    		<th style="color:#FFF; padding:6px 0px;" width="40%">Date</th>
                    		<th style="color:#FFF; padding:6px 0px;" width="40%">Day</th>
                            <th style="color:#FFF; padding:6px 0px;" width="40%">Time</th> 							
						</tr>
					</thead>
                    <tbody>
                    	<?php 
						$this->db->select('subject.name as subject_name,exam.name as exam_name,exam.class_id,exam.subject_id,exam.date,exam.time_start,exam.time_end');
						$this->db->join('subject', 'subject.subject_id = exam.subject_id');
					$exam = $this->db->get_where('exam',array('exam.class_id'=>$class_id,'exam.exam_id'=>$exam_id))->result_array();
						foreach($exam as $row_exam):	?>
                        <tr>
                            <td align="center" style="font-size:12px; padding:6px 0px; border-bottom:1px solid #EEE; border-left:1px solid #EEE; border-right:1px solid #EEE;" width="10%"><?php echo $row_exam['subject_name'];?></td>
							<td align="center" style="font-size:12px; padding:6px 0px; border-bottom:1px solid #EEE; border-left:0px solid #EEE; border-right:0px solid #EEE;" width="25%" ><?php echo date("F d, Y",strtotime($row_exam['date']));?></td>
							<td align="center" style="font-size:12px; padding:6px 0px; border-bottom:1px solid #EEE; border-left:0px solid #EEE; border-right:0px solid #EEE;" width="25%"><?php echo date("l", strtotime($row_exam['date']));?></td>
                            <td align="center" style="font-size:12px; padding:6px 0px; border-bottom:1px solid #EEE; border-left:0px solid #EEE; border-right:0px solid #EEE;" width="25%"><?php echo $row_exam['time_start'].' TO '.$row_exam['time_end'];?></td>
                        </tr>
                        <?php endforeach; ?>
                    </tbody>
                    
                     <tr>
                        <td valign="middle" align="right" colspan="4" style="padding:12px 2px; border-top:2px solid #2092D0; "><span style="color:#2092D0;">Generated By : </span> <?php echo $this->session->userdata('name');?> </td>
                        </tr>
                    	
                </table>
                
			</div>
            <!----TABLE LISTING ENDS--->
		</div>
	</div>
</div>



