

<div class="row">
	<div class="col-md-12"> 
		<div class="tab-content">
            <!----TABLE LISTING STARTS-->
            <div class="tab-pane box active" id="list" style="width:100%;">
            
          
                 <table class="table datatable table" border="0" cellpadding="0" cellspacing="0" style="width:100%; font-family:Arial, Helvetica, sans-serif; font-size:14px; letter-spacing:0.5;" id="table_export">
                	<thead>
                   <tr>
                            <td colspan="7">
                                <table width="100%">
                                    <tr>
                                        <td width="33.33%"  valign="middle" align="left";><div><?php  $image = base_url().'/uploads/system_image/1.jpg'; ?>
                                        <img src="<?php echo $image; ?>" width="80" height="70" /></div></td>
                                        <td width="33.33%" valign="middle" align="center"><div style="font-size:1.8em; text-align:center; font-weight:600; color:#000;">Page Inc School</div></td>
                                        <td width="33.33%" valign="bottom" align="right" style="font-size:12px;"><div>Date : <?php echo date('jS M Y'); ?> </div></td>     
                                    </tr>
                                </table>
                            </td>
                    </tr>
                        <tr><td colspan="7" style="height:15px;"></td></tr>
                        <tr bgcolor="#000000"><td colspan="7" style="font-size:1.2em; text-align:center; font-weight:600; padding:6px 0px; color:#FFF;">Fees Listing</td></tr>
                		
                        <tr bgcolor="#2092D0">
                    		<th  style="color:#FFF; padding:6px 2px; width:14.28%; ">No</th>
                    		<th style="color:#FFF; padding:6px 2px; width:14.28%;" >Date</th>
                    		<th style="color:#FFF; padding:6px 2px; width:14.28%;">Student</th> 
                    		<th style="color:#FFF; padding:6px 2px; width:14.28%;">Total</th>  
                    		<th style="color:#FFF; padding:6px 2px; width:14.28%;" >Paid</th> 
                    		<th style="color:#FFF; padding:6px 2px; width:14.28%;" >MOP</th>  
                    		<th style="color:#FFF; padding:6px 2px; width:14.28%;" >Description</th>  
						</tr>
					</thead>
                    <tbody>
                    	<?php 
						$student_id = $this->session->userdata('student_id');
						$invoices =   $this->db->get_where('invoice',array("student_id"=>$student_id))->result_array();
						$count = 1;
					
						foreach($invoices as $row):						
						?>
                        <tr>
                            <td align="center" style="font-size:11px; padding:6px 0px; border-bottom:1px solid #EEE; border-left:1px solid #EEE; border-right:1px solid #EEE;  width:14.28%; "><?php echo $count++;?></td>
							<td align="center" style="font-size:11px; padding:6px 0px; border-bottom:1px solid #EEE; border-left:1px solid #EEE; border-right:1px solid #EEE;  width:14.28%; "><?php echo date('d M,Y', $row['creation_timestamp']);?></td>
							<td align="center" style="font-size:11px; padding:6px 0px; border-bottom:1px solid #EEE; border-left:1px solid #EEE; border-right:1px solid #EEE; width:14.28%;"><?php echo @$this->crud_model->get_type_name_by_id('student',$row['student_id']);?></td>
							<td align="center" style="font-size:11px; padding:6px 0px; border-bottom:1px solid #EEE; border-left:1px solid #EEE; border-right:1px solid #EEE; width:14.28%;"><?php echo $row['amount'];?></td>
							<td align="center" style="font-size:11px; padding:6px 0px; border-bottom:1px solid #EEE; border-left:1px solid #EEE; border-right:1px solid #EEE; width:14.28%;"><?php echo $row['amount_paid'];?></td>
							<td align="center" style="font-size:11px; padding:6px 0px; border-bottom:1px solid #EEE; border-left:1px solid #EEE; border-right:1px solid #EEE; width:14.28%;"><?php echo $row['payment_method'];?></td>
							<td align="center" style="font-size:11px; padding:6px 0px; border-bottom:1px solid #EEE; border-left:1px solid #EEE; border-right:1px solid #EEE; width:14.28%;"><?php echo $row['description'];?></td>
                        </tr>
                         <?php endforeach;
						?>
                    </tbody>
					<tr>
                        <td valign="middle" align="right" colspan="7" style="padding:12px 0px; border-top:2px solid #2092D0; font-size:10px;"><span style="color:#2092D0;">Generated By : </span> <?php echo $this->session->userdata('name');?> </td>
                    </tr>
                </table>
                
			</div>
            <!--TABLE LISTING ENDS-->
		</div>
	</div>
</div>



